### ISSUE TITLE
mp4 only plays in Chromium/Chrome

### ISSUE THREAD

**Issue by pmaier1** [owncloud/files_mediaviewer#101]
With FF/Edge Videos don't play neither in public links nor as an authenticated user. Did not test other formats.

![Screenshot from 2019-07-16 14-39-58](https://user-images.githubusercontent.com/21193500/61295232-dd0dff00-a7d7-11e9-8d64-024c7e8b0ee9.png)
![Screenshot from 2019-07-16 14-39-46](https://user-images.githubusercontent.com/21193500/61295238-df705900-a7d7-11e9-9ad8-c7b3829a29b0.png)

You can try here: https://cloud.wgserv.eu/s/ntZsXU6gxxwOqA0#/

**Comment by davitol** [comment]
@pmaier1 Just added to the link the mp4 video file used for testing purpose and it can be reproduced

**Comment by davitol** [comment]
Tried with 3 more mp4 files and all worked fine in the supported browsers.
I downloaded the files that were uploaded to the public link and we were not able to plays and tried to play them in local with Quicktime. They also failed in local (The document “dropbox_take1.mp4” could not be opened.)
So the issue is probably specific of the mp4 files.
@pmaier1 Should be close this ticket? Kind of dupe of https://github.com/owncloud/files_mediaviewer/issues/98

**Comment by pmaier1** [comment]
> @pmaier1 Should be close this ticket? Kind of dupe of #98

Kind of, except that the videos don't play at all. For now this really seems to be specific to the files I uploaded. I checked codec information with VLC:

**Does not work**
![Screenshot from 2019-07-16 17-20-45](https://user-images.githubusercontent.com/21193500/61307232-40a32700-a7ee-11e9-9667-ef033b80cc9c.png)

**Works**
![Screenshot from 2019-07-16 17-21-29](https://user-images.githubusercontent.com/21193500/61307253-46990800-a7ee-11e9-8a50-a3313e4aa5aa.png)

Maybe that helps somehow. If it's really just my two files that can't be played, maybe we should not invest more time in this.

**Comment by DeepDiver1975** [comment]
Used codecs:

![Screenshot from 2019-07-16 17-23-51](https://user-images.githubusercontent.com/1005065/61307392-85c75900-a7ee-11e9-8552-f42112d13527.png)

**Comment by pmaier1** [comment]
Seems the issue has to do with "Decoded format: Planar 4:4:4 YUV". The error in the browser console mentions that.

**Comment by pmaier1** [comment]
Here we go https://bugzilla.mozilla.org/show_bug.cgi?id=1368063#c4
Please reopen if you see a necessity.
