### ISSUE TITLE
[Mobile] Mediaviewer not working properly on mobile view

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/files_mediaviewer#135]
I just tested the Mediaviewer on my Huawei P30 Pro in a Chrome mobile browser. 

### Actual behavior
The viewer is not above the mobile view of the files view.

![Screenshot_20191023_015900_com android chrome](https://user-images.githubusercontent.com/33026403/67344849-44ef8680-f539-11e9-94d3-d403072ec580.jpg)

### Expected behavior
The viewer appears on the level between the header and the mobile files view.

ownCloud Version: 10.3.0

@felixheidecke FYI

https://github.com/owncloud/files_mediaviewer/blob/0bc52bd15312b4fc39059517499343f5533d7b75/src/styles/_base.scss#L5

I tested the value `1000` here. Should work.

**Comment by DeepDiver1975** [comment]
> I tested the value `1000` here. Should work.

mind submitting a PR? THX

**Comment by ChrisEdS** [comment]
Sure.

**Comment by pmaier1** [comment]
Just tried it out of curiosity. On my FF 68.1.1 on Android it doesn't open pictures at all. You click on it and nothing happens.

**Comment by ChrisEdS** [comment]
I will fix today.
