### ISSUE TITLE
[Mobile View Fix] Files Mediaviewer 1.0.1

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/files_mediaviewer#140]
### Reason

- Release needed for https://github.com/owncloud/files_mediaviewer/pull/136, "Mobile browser view fix"

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [ ] Create "$version Testplan"

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch @ChrisEdS 

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Smoke test tarball (at least install + enable) @micbar 

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number

**Comment by ChrisEdS** [comment]
I tested I have tested on platforms and browsers whether the player is displayed after my change. I can confirm this. Since I only changed one value we can start the release process.

**Comment by micbar** [comment]
@ChrisEdS RC1 in https://github.com/owncloud/files_mediaviewer/releases/tag/v1.0.1RC1

Needs quick smoke test.

**Comment by ChrisEdS** [comment]
The smoke test went fine. Please release.
