### ISSUE TITLE
Add Support for playing Apple Quicktime (*.mov)

### ISSUE THREAD

**Issue by TDannhauer** [owncloud/files_mediaviewer#169]
Since *.mov Files are iOS standard, please add the ability to stream theses files in the app as well.

The mimetype ist "video\quicktime".

Thanks!

**Comment by jaccol** [comment]
adding "video/quicktime" to the mimetypes array in both `apps/files_mediaviewer/js/files_mediaviewer.js` and `apps/files_mediaviewer/js/files_mediaviewer_init.js` did the trick for me. quicktime videos worked immediately.

**Comment by mmattel** [comment]
@felixheidecke 
this could be an easy win before a new release gets published

**Comment by TDannhauer** [comment]
Will someone integrate in the code to integrate the ability into the new release?

**Comment by DeepDiver1975** [comment]
You know how open source works? Open a pull request and things could go a bit faster ;-)

**Comment by mmattel** [comment]
@DeepDiver1975, you can now approve and merge the fix for this issue #194, thanks :smile:
