### ISSUE TITLE
Public link capability

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/files_mediaviewer#17]
We may need to allow the media to be viewed in public links. Thus a solution for [thumbnail generation](https://github.com/owncloud/files_mediaviewer/blob/master/src/scripts/Viewer.vue#L40) using `OC.getCurrentUser()` needs to be found.

**Comment by PVince81** [comment]
@felixheidecke we have a different Webdav URL for public links. It might just be a matter of using it and appending the preview flag

**Comment by PVince81** [comment]
@felixheidecke you might be able to get the preview URL from the FileList instance. Maybe `FileList.filesClients.getBaseUrl()` ?

**Comment by PVince81** [comment]
@felixheidecke please check what the network console shows, the URLs must be sthe same.

You might need to get the user id information or even auth header information and pass it to the pic/video viewer. See https://github.com/owncloud/core/blob/stable10/apps/files/js/file-upload.js#L258

**Comment by felixheidecke** [comment]
The URLs sure do differ from one another:

User: `/remote.php/dav/files/admin/image.jpg?c=...`
Public: `/public.php/webdav/image.jpg?c=...`

Yet I found out that I can use the files_sharing app to create a preview:
`/index.php/apps/files_sharing/ajax/publicpreview.php?file=image.jpg&c=...`

@PVince81 might that be a valid approach?

**Comment by PVince81** [comment]
@DeepDiver1975 did we not add the new preview format on the public endpoint ?

if this is missing let's raise a ticket in core and use the "publicpreview.php" endpoint then

**Comment by PVince81** [comment]
> Still trying to figure out how to detect its a public link or not, couldn't find any docs.

seems we're missing an API for that as well...

you could try detecting if the "OC.Sharing.PublicApp" is defined... then raise a ticket in core for some cleaner stuff

**Comment by PVince81** [comment]
- [ ] retrieve correct webdav path
- [ ] make sure to encode path sections if not already (see https://github.com/owncloud/files_mediaviewer/issues/28#issuecomment-462731836)

**Comment by felixheidecke** [comment]
Going back to https://github.com/owncloud/files_mediaviewer/issues/28#issuecomment-462729632 … do all three videos play back correctly?
