### ISSUE TITLE
Open BUMP´s

### ISSUE THREAD

**Issue by mmattel** [owncloud/files_mediaviewer#199]
@micbar @phil-davis 
There are a lot of open bumps which should be checked if mergable or not.
Atm, there is no CI to proof working so this is a manual task.
Pls either add a CI for proving this or ask eg @felixheidecke to do so as he has the best knowledge about this repro.

**Comment by phil-davis** [comment]
PR #186 has "security" tag.

**Comment by mmattel** [comment]
The majority of the bumps are now merged, closing
