### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_mediaviewer#213]
There are places in the code that "mark" strings for translation, e.g.
https://github.com/owncloud/files_mediaviewer/blob/master/src/scripts/ViewerControlsImage.vue#L8
```
		<div class="viewer__controls__subgroup">
			<button class="viewer__control icon__rotate_90_degrees_ccw" @click="rotate(rotation - 90)" v-translate>Rotate 90° counterclockwise</button>
			<button class="viewer__control icon__zoom_in" @click="scale(scaling + .2)" v-translate>Zoom in</button>
			<button class="viewer__control icon__zoom_out" @click="scale(scaling - .2)" v-translate>Zoom out</button>
		</div>
```

1) do we want translations available for those?
2) if so, then do they get translated already "by some magic"?
3) if we need, then how do we setup translations?

**Comment by phil-davis** [comment]
@HanaGemela @davitol maybe one of you, or "somebody", can start with the first 2 questions.

**Comment by davitol** [comment]
>     1. do we want translations available for those?

IMHO not worthy. Words like zoom are international enough. Also the icons for the mediaviewer are clear. BUt as said, it is just an opinion.

**Comment by phil-davis** [comment]
The `v-translate` words are:
```
Loading
Rotate counterclockwise
Zoom in
Zoom out
Download
Close
Previous
Next
Replay
Mute
Fullscreen
```
Somebody can decide if there should be translations available.
If not., then close this issue.

**Comment by HanaGemela** [comment]
"Somebody" in this case is @pmaier1 

The requirement is 100% strings are translated for each app. I haven't heard about any exceptions. 
The issue is the process "how to do it" is missing. We'll arrange a meeting

**Comment by DeepDiver1975** [comment]
Ping me of translation is not properly setup.

**Comment by HanaGemela** [comment]
Answers for the questions:
1. Yes, everything has to be translated
2. @pmaier1 will make sure it gets translated
3. @DeepDiver1975 please make sure translations are correctly setup

**Comment by DeepDiver1975** [comment]
https://www.transifex.com/owncloud-org/owncloud/files_mediaviewer/

**Comment by DeepDiver1975** [comment]
and done - https://github.com/owncloud/translation-sync/pull/34
