### ISSUE TITLE
Files mediaviewer 1.0.3

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/files_mediaviewer#220]
### Reason

- [x] https://github.com/owncloud/files_mediaviewer/issues/213

### QA

- [x] Translation meeting
- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "1.0.3 Testplan" @davitol https://github.com/owncloud/files_mediaviewer/issues/271

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing
- [x] Ping pmaier to check `info.xml` description and screenshot

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => @davitol https://github.com/owncloud/files_mediaviewer/issues/271

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by mmattel** [comment]
@HanaGemela 
we have another reason for a new release, #225 
What are the plans creating a new release?
(Would be great to publish it)

**Comment by HanaGemela** [comment]
@mmattel moved the ticket to Qualification column for the management to consider a new release

**Comment by HanaGemela** [comment]
@mmattel This has been moved to the "Dev done, RC needed" column. The release process has started

**Comment by HanaGemela** [comment]
@davitol RC1 https://github.com/owncloud/files_mediaviewer/releases/tag/v1.0.3RC1

**Comment by davitol** [comment]
> @davitol RC1 https://github.com/owncloud/files_mediaviewer/releases/tag/v1.0.3RC1

 Add l10n support - #217 **l10n folder is not present in the RC1 tarball**

**Comment by phil-davis** [comment]
See #273 Include l10n in tarball

**Comment by jnweiger** [comment]
@davitol RC2 is ready for testing https://github.com/owncloud/files_mediaviewer/releases/tag/v1.0.3RC2

**Comment by davitol** [comment]
> @davitol RC2 is ready for testing https://github.com/owncloud/files_mediaviewer/releases/tag/v1.0.3RC2
> Will also be included in the owncloud-10.5.0RC4 server bundles.

Final is already released. Sanity tested and LGTM. Let's close this ticket

**Comment by HanaGemela** [comment]
Publishing and post-release steps still to be done
