### ISSUE TITLE
Run it locally in a browser

### ISSUE THREAD

**Issue by dabrain34** [owncloud/files_mediaviewer#246]
I'd like to add a feature to this module but first I need to know to how get started.

Is there a wiki on how to test/run this webapp in a browser ? 

When I run yarn install, i'm getting

```
yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
```

**Comment by karakayasemi** [comment]
@dabrain34 Your problem can be specific to your development environment. I have found several solutions on the web like this one about your issue https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install

Can you try these solutions and report back result? Thanks.

**Comment by dabrain34** [comment]
Thx this is working on Ubuntu 18.04 with 

```
$ sudo apt remove cmdtest
$ sudo apt install npm
$ sudo npm install -g yarn
```

**Comment by dabrain34** [comment]
And then after install and build as described in the README.md, do you think I can test the player outside of owncloud ? Is there a way to test the player only ?

**Comment by karakayasemi** [comment]
I assume the player is using ownCloud APIs to read media files. I could not find a quick way to test without ownCloud. 🤷‍♂️ 

If you think the described problem of the issue resolved, please close this issue. For further questions, you can use public Rocket.Chat instance of ownCloud https://talk.owncloud.com/ and community forum https://central.owncloud.org. Thanks.

**Comment by dabrain34** [comment]
I thought it could be interesting to add some documentation in the readme.md on how to install the plugin/app in owncloud or at least provide a link for a generic way.

**Comment by dabrain34** [comment]
@karakayasemi Is there a way to test a local version of this app within a docker by example ?

Can you point me to a documentation on how I could be started with `hacking into the code` :) ?

**Comment by karakayasemi** [comment]
@dabrain34 I guess this answer is valid for your problem also https://github.com/owncloud/files_mediaviewer/issues/247#issuecomment-634467555

After building your modified application, just copy it to apps folder of your server instance.
