### ISSUE TITLE
Apply script to image before it is displayed

### ISSUE THREAD

**Issue by DarkNavrel** [owncloud/files_mediaviewer#256]
How can I create a function that passes an image in a javascript before being displayed. I mean, when a user accesses a folder and clicks on an image, the system will deliver it to a javascript, the javascript will receive the image and render it again and return modification to mediaViewer. (I already have this javascript to make the modification to the image) but as I have no experience with VUE so I couldn't find a good way to add this in the native code.

Thanks to everyone who answered.

**Comment by DeepDiver1975** [comment]
One would need to rewrite the image loading logic in https://github.com/owncloud/files_mediaviewer/blob/master/src/scripts/Viewer.vue 
Or you put your logic into https://github.com/owncloud/files_mediaviewer/blob/master/src/scripts/ViewerControlsImage.vue where image manipulations like rotate are already implemented.

Have fun!
