### ISSUE TITLE
Features / Next steps

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/files_mediaviewer#3]
As discussed with @pmaier1 and @michaelstingl, we decided to drop the [Album-View](https://github.com/owncloud/enterprise/issues/2711#issuecomment-440247391) and write a new fullscreen view e. g. lightbox for OC10.

### Features

- Image gallery view (full screen)
- Video gallery view (full screen)
- Display filename
- Next & Prev mediafile navigation
- Image rotation
- Media removal (delete the file)
- Media download (download current file)
- Autoplay
- Integrated with public link files view (single file / folder)

Architecture to Phoenix differs greatly, so this rewrite will be oc10 only! Concepts for a Media Gallery App for Phoenix will happen in a different/new Issue.

### Next Steps

- [x] Estimate time needed for frontend rewrite
- [x] Estimate time needed for backend rewrite
- [x] Check if there are available routes in core for thumbnail generation
- [x] Determine image generation API endpoint
- [x] Create endpoint for listing eligible media files

This should look somewhat like this:

```
[
    {
        "id" : 12312,
        "filename" : "klaus.jpg",
        "mimetype" : "image/jpeg",
        "filesize" : 1254830,
        "size" : {
            "width" : 1280,
            "height" : 1024
        }
    }, {
        "id" : 12313,
        "filename" : "wedding_fails.mp4",
        "mimetype" : "video/mp4",
        "filesize" : 51238453,
        "size" : {
            "width" : 1920,
            "height" : 1080
        }
    }
]
```

**Comment by PVince81** [comment]
please update checkboxes.

maybe also link some with the tickets you raised

**Comment by michaelstingl** [comment]
@felixheidecke close this?
