### ISSUE TITLE
Files mediaviewer 1.0.4

### ISSUE THREAD

**Issue by mmattel** [owncloud/files_mediaviewer#324]
### Reason

The last release was made in July (v1.0.3).  in the meanwhile, additional fixes/improvements and security bumps are merged:

- Add icon and correct text in the file actions menu - [#337](https://github.com/owncloud/files_mediaviewer/pull/337)
- Possibly fix Gallery & files_mediaviewer compatibility issue - [#310](https://github.com/owncloud/files_mediaviewer/pull/310)
- Add bgcolor and adopt the height of the video scrubber - [#287](https://github.com/owncloud/files_mediaviewer/pull/287)

### Product approval 

- [x] Verify transifex commits are in master: If a folder https://github.com/owncloud/files_mediaviewer/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/files_mediaviewer should receive nightly '[tx] updated from transifex` ...
- [x] Ping pmaier to check `info.xml` description and screenshot
- [x] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [ ] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" https://github.com/owncloud/files_mediaviewer/issues/349

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers (see handbook in confluence for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [ ] Rename QA milestone to `$version`
- [ ] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [ ] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [ ] Close the milestone
- [ ] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by jnweiger** [comment]
* [x] Confirmed #310: When gallery 16.1.1 is also enabled, it works perfectly fine.

**Comment by pmaier1** [comment]
Thanks! The release is mainly for allowing compatibility between Media Viewer and Gallery. No regressions, no blockers.

**Comment by mmattel** [comment]
v1.0.4 is availalbe on the marketplace, I think that this issue can be closed.
Any open items should be moved to a "to be created" 1.0.5 issue.
