### ISSUE TITLE
Renaming files mess up slides order

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_mediaviewer#34]
### Steps

1. Have a folder with many files in it
1. Have a file at the top, for example called "a.mp4"
1. Open the viewer
1. Close the viewer
1. Rename "a.mp4" to "t.mp4" to make it appear near the end
1. Click on "t.mp4"

### Expected result
"t.mp4" appears

### Actual result
Another file appears

### Version
master

@felixheidecke are we properly resetting the viewer after closing ?

I remember we discussed keeping it alive. We should at least reset its store then and get the store populated again the next time it opens.

**Comment by felixheidecke** [comment]
Yes we do reset the filelist once someone re-opens the list. I just found out, that renaming a file has the following effekt on FileList.files:

![bildschirmfoto 2019-02-13 um 11 41 12](https://user-images.githubusercontent.com/12717530/52705928-69e03280-2f84-11e9-9a62-809d6bb84166.png)

The first two items in the list have been renamend. All other keys are dropped in their respective object, or rather a new object is set only containing only the name. Bug … I guess?

**Comment by felixheidecke** [comment]
After renaming, the FileList.files looses cohesion: After some renaming, it turs from this:

![bildschirmfoto 2019-02-13 um 11 52 14](https://user-images.githubusercontent.com/12717530/52706512-e1fb2800-2f85-11e9-86db-80fe07cf6dbf.png)

into this:

![bildschirmfoto 2019-02-13 um 11 52 21](https://user-images.githubusercontent.com/12717530/52706527-e7f10900-2f85-11e9-8039-5a8a4f570f72.png)

**Comment by PVince81** [comment]
@felixheidecke didn't you fix that already on the viewer side ?

**Comment by PVince81** [comment]
works fine now in 1.0.0RC1
