### ISSUE TITLE
Proper error in case of failed playback

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_mediaviewer#35]
### Steps

1. Upload two videos "1.mp4" and "2.mp4".
1. Open "1.mp4" in the viewer but don't start playback
1. Open a second browser tab and delete "1.mp4"
1. Go back to first browser tab and start playback

### Expected result
Proper error message

### Actual result
No error message, errors in console.

**Comment by skshetry** [comment]
When on Edge, I see that the viewer's position changed when played.


![edge](https://user-images.githubusercontent.com/18718008/57119138-ae12f000-6d87-11e9-95b8-7fded5e244e9.gif)
