### ISSUE TITLE
First video in list doesn't play

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_mediaviewer#37]
### Steps

0. Create an empty folder
1. Upload a bunch of supported videos
2. Rename them "01.mp4", "02.mp4" and "03.mp4"
3. Refresh the page
4. Watch "01.mp4" => fail
5. Watch "02.mp4" => success
5. Now rename and swap 01 with 02
6. Refresh the page
7. Watch the new "01.mp4" => fail
8. Watch the  "02.mp4" which was 01 => success

I suspect that there might be a bug in the preloading.

@felixheidecke

**Comment by felixheidecke** [comment]
Being fixed in https://github.com/owncloud/files_mediaviewer/pull/36

**Comment by alariej** [comment]
I am on OC 10.3.2.2 with Media Viewer 1.0.1 and I have the exact same problem. First video in a URL-shared folder doesn't play. No error message, no still image, no sound, nothing. Tested on desktop (Firefox, Chrome), iOS (Firefox, Safari), Android (Firefox, Chrome). Same thing everywhere. Videos are .mp4. Has this really been fixed?
