### ISSUE TITLE
Button for fullscreen mode

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_mediaviewer#38]
The old video player had a button for full screen mode.

Would be good to be able to watch videos, or even browse the slideshow in full screen mode, in which case the picture must take the whole screen and the transparent background becomes black.

If too complicated then fullscreen video would already be nice.

@pmaier1 @felixheidecke

**Comment by pmaier1** [comment]
Fullscreen mode should be available for the initial release, IMO. @felixheidecke anyway planned to add this afaik.

**Comment by felixheidecke** [comment]
Is it fine if we try to release without fullscreen and put it in, in a 1.1.0?
Let's get some hands-on and feedback.

**Comment by PVince81** [comment]
yes, ticket is already backlogged

**Comment by PVince81** [comment]
@felixheidecke estimate for fullscreen ? or need more research ?

**Comment by felixheidecke** [comment]
I have a plan, but not sure if it works that way. Let's estimate 3hrs on that one.

**Comment by PVince81** [comment]
as discussed, let's do this for 1.0.0

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/files_mediaviewer/pull/45
