### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by youradds** [owncloud/files_mediaviewer#388]
Hi,

I'm trying to work out how to install this. I've downloaded the ZIP and uploaded it to:

/home/drive/web/foo.site.com/public_html/apps/files_mediaviewer

` yarn install && yarn build`

..but all that gets me is:

```
yarn install && yarn build
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
```

What am I doing wrong? I'm not used to manually installing plugins on stuff =) (especially where you have to configure it)

TIA

Andy

**Comment by JanAckermann** [comment]
Seems like you did not unpack the zip file, this needs to be done (and navigate into the folder), before running any yarn commands
