### ISSUE TITLE
[TODO] Research listing and file dimensions

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/files_mediaviewer#4]
We need an endpoint for listing eligible media files that include some basic props. What ever data a propfind can reveal, let's just put it in ;-)
This should resemble an array of objects like this:
```
[
    {
        "id" : 12312,
        "filename" : "klaus.jpg",
        "mimetype" : "image/jpeg",
        "filesize" : 1254830,
        "size" : {
            "width" : 1280,
            "height" : 1024
        }
    }, {
        "id" : 12313,
        "filename" : "wedding_fails.mp4",
        "mimetype" : "video/mp4",
        "filesize" : 51238453,
        "size" : {
            "width" : 1920,
            "height" : 1080
        }
    }
]
```

**Comment by felixheidecke** [comment]
`FileList.files` may help. Need help enriching it with propfind(s).

**Comment by PVince81** [comment]
there is no JSON endpoint, only Webdav.

the app shouldn't need this, you can simply access the file list through the file actions callback. See https://github.com/owncloud/gallery/blob/master/js/galleryfileaction.js#L51 and the onView callback.
You'll get access to the current `FileList` instance as here: https://github.com/owncloud/gallery/blob/master/js/galleryfileaction.js#L86

The FileList is this class: https://github.com/owncloud/core/blob/v10.0.10/apps/files/js/filelist.js#L36

**Comment by felixheidecke** [comment]
After some researching, I found out that the current gallery receives thumbnails as a base64 encoded stream, writes them to the DOM, then measures the dimensions, writes them back to DOM as inline CSS … yeah, an already ugly jquery-style hack. The current gallery rendering process looks "as thou it was intended" but the jumpiness is actually the write-read-write process going on.

**Comment by PVince81** [comment]
should be possible to use offscreen rendering then for the measurement

**Comment by felixheidecke** [comment]
Problem has been solved.
