### ISSUE TITLE
Spinner doesn't disappear after loading image

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_mediaviewer#43]
### Steps

1. Create folder "test"
1. Upload 10+ images.
1. Open JS console
1. Click on second image
1. Wait for load

### Expected result
After loading uncached image, spinner disappears.

### Actual result
Spinner stays, JS error:
![image](https://user-images.githubusercontent.com/277525/52974401-b29f4d80-33c1-11e9-9fd4-52aaf21446c0.png)

### Version
master b3fa5756b2ad8a9a66975d5cb14767bd5260b60f

@felixheidecke please have a look. Need to fix before release.

**Comment by PVince81** [comment]
This is on Firefox 64.

From what I remember on Chromium the spinner seemed to disappear correctly.

**Comment by felixheidecke** [comment]
I experience these errors ONLY when I have the developer console open. If not, it all works just fine?! What's wrong here? Is devcon messing up my script?

**Comment by felixheidecke** [comment]
- [ ] Test if this happens with devcon off

**Comment by PVince81** [comment]
@felixheidecke can you test and confirm so we can close this ?

In my latest tests I didn't see this happening any more, so from my side we could close

**Comment by felixheidecke** [comment]
Doesn't happen to me either. So I'll close.
