### ISSUE TITLE
Feedback on 1.0.0beta

### ISSUE THREAD

**Issue by pmaier1** [owncloud/files_mediaviewer#50]
Just dropped https://github.com/owncloud/files_mediaviewer/releases/tag/v1.0.0beta into my private instance and gave it a shot. Here's what I found:

- I didn't find a way to start image slideshow. How does it work?
- You can only close the slideshow view when clicking on "x". As a user I would have expected the view to also close when clicking somewhere in the white space (outside the image/video). This was the case with Gallery as well afair.
- When viewing a video the control button left of "Play" looks similar to the "image rotation" button but it does have different functionality: It rewinds the video to the beginning. This was very confusing to me. If we really need a button to rewind (you can also use the fader..), then we should have a better icon.
- No fullscreen mode for pictures? Probably on purpose, just wanted to ask :)
- In other players videos usually have some overlay circle with a "play" icon in it that indicates it can be played. I'm missing a video indicator when navigating between images and videos in slideshow view.

@PVince81 @felixheidecke

**Comment by PVince81** [comment]
@pmaier1 if you had an older version please make sure to clear the cache. Videos should now have a circled play icon right in the middle. See

**Comment by PVince81** [comment]
- [ ] minor: cannot decode image: https://github.com/owncloud/files_mediaviewer/issues/51

**Comment by PVince81** [comment]
> I didn't find a way to start image slideshow. How does it work?

you mean a timed slideshow ? there is no such feature and it wasn't clear to me that it was a requirement but should have guessed from the old gallery. Raised here: https://github.com/owncloud/files_mediaviewer/issues/52

> You can only close the slideshow view when clicking on "x". As a user I would have expected the view to also close when clicking somewhere in the white space (outside the image/video). This was the case with Gallery as well afair.

raised https://github.com/owncloud/files_mediaviewer/issues/53

> No fullscreen mode for pictures? Probably on purpose, just wanted to ask :)

raised https://github.com/owncloud/files_mediaviewer/issues/54

> In other players videos usually have some overlay circle with a "play" icon in it that indicates it can be played. I'm missing a video indicator when navigating between images and videos in slideshow view.

we already have this, not sure why you don't see it

**Comment by PVince81** [comment]
closing this as I've raised separate tickets.

**Comment by PVince81** [comment]
raised https://github.com/owncloud/files_mediaviewer/issues/56 for invisible play button
