### ISSUE TITLE
Cannot decode image

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_mediaviewer#51]
While loading a non-buffered non cached picture, this appears in the console log:
![image](https://user-images.githubusercontent.com/277525/54025733-bbeb3100-419b-11e9-867d-de3bfce98964.png)

the picture still loads though

@felixheidecke

**Comment by PVince81** [comment]
this is on openSUSE Tumbleweed with Firefox 64.0

**Comment by PVince81** [comment]
another one that happen while I switched faster:
![image](https://user-images.githubusercontent.com/277525/54025896-42077780-419c-11e9-9877-90db26e0a917.png)

pics still appear though

**Comment by felixheidecke** [comment]
> While loading a non-buffered non cached picture, this appears in the console log:

Dangit … let's see what's up with that.

**Comment by felixheidecke** [comment]
Est. 2h.
