### ISSUE TITLE
Close lightbox while clicking on the empty space around the picture

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_mediaviewer#53]
> You can only close the slideshow view when clicking on "x". As a user I would have expected the view to also close when clicking somewhere in the white space (outside the image/video). This was the case with Gallery as well afair.

From https://github.com/owncloud/files_mediaviewer/issues/50

I noticed that in touch mode I can also swipe from the empty space.
I guess we need to also detect taps there for closing.

**Comment by felixheidecke** [comment]
Est. 1h
