### ISSUE TITLE
Issues with Firefox 65 and HTTPS Everywhere extension

### ISSUE THREAD

**Issue by pmaier1** [owncloud/files_mediaviewer#57]
On my Firefox 65 I have issues when the extension "HTTPS Everywhere" is enabled. When disabling it, all works well.

![screenshot from 2019-03-06 14-49-05](https://user-images.githubusercontent.com/21193500/54038625-41cda300-41c1-11e9-9893-553d1be2083d.png)

![screenshot from 2019-03-06 14-47-15](https://user-images.githubusercontent.com/21193500/54038635-485c1a80-41c1-11e9-9194-c90d1be18cf4.png)

**Comment by felixheidecke** [comment]
![Bildschirmfoto 2019-03-15 um 17 04 04](https://user-images.githubusercontent.com/12717530/54445077-5c18fb00-4744-11e9-9c1b-93df17d1c927.png)
![Bildschirmfoto 2019-03-15 um 17 03 54](https://user-images.githubusercontent.com/12717530/54445080-5c18fb00-4744-11e9-8c1c-41f4deba2526.png)

**Comment by felixheidecke** [comment]
Works fine with me. Not sure what the "HTTPS Everywhere" does and how so I suggest disabling it then ;-)

**Comment by felixheidecke** [comment]
This has been solved in https://github.com/owncloud/files_mediaviewer/pull/59
