### ISSUE TITLE
Image and icon for files_mediaviewer

### ISSUE THREAD

**Issue by mmattel** [owncloud/files_mediaviewer#6]
We need a image and a icon for this new app which should be inline with the new images already created.

@hurradieweltgehtunter

**Comment by mmattel** [comment]
@PVince81 @hurradieweltgehtunter 
A reminder that this is needed.

**Comment by hurradieweltgehtunter** [comment]
release ETA for app? 
@PVince81

**Comment by pmaier1** [comment]
> release ETA for app?

In February, I'd say.

**Comment by mmattel** [comment]
Any update?

**Comment by hurradieweltgehtunter** [comment]
working on it

**Comment by hurradieweltgehtunter** [comment]
Image is here: https://github.com/owncloud/screenshots/blob/master/files_mediaviewer/ownCloud-app-media-viewer.jpg

![owncloud-app-media-viewer](https://user-images.githubusercontent.com/16665512/53653810-8058e000-3c4c-11e9-986c-3293bcb4879c.jpg)

Icon will follow in the next few days

**Comment by pmaier1** [comment]
The mediaviewer can only display images and videos. It can't play music.

**Comment by hurradieweltgehtunter** [comment]
so the image is futureproof? :D
Rework needed or can we go along with it?

**Comment by pmaier1** [comment]
In the context of ownCloud 10 the mediaviewer will never play music, sorry. :)

**Comment by hurradieweltgehtunter** [comment]
Updated
[](https://raw.githubusercontent.com/owncloud/screenshots/master/files_mediaviewer/ownCloud-app-mediaviewer.jpg)

**Comment by PVince81** [comment]
done and included in 1.0.0RC1
