### ISSUE TITLE
Add SVG support

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_mediaviewer#65]
@pmaier1 FYI

assuming it's just a one liner to add the relevant mime type + quick test ? @felixheidecke 

please PR to "release-1.0.0" branch

**Comment by PVince81** [comment]
what to do with transparent colors ? => check how the old gallery did it

**Comment by felixheidecke** [comment]
Hmmm … I just found out, that core thumb creator doesn't support SVG files, so it throws an error. @PVince81 Should I implement an image mime type specific list on when to use what path?

**Comment by PVince81** [comment]
@felixheidecke you need to enable it explicitly: https://github.com/owncloud/core/blob/v10.1.1/config/config.sample.php#L836

**Comment by PVince81** [comment]
the server exposes the supported registered preview mime types in `OC.appConfig.core.enabledPreviewProviders`. see https://github.com/owncloud/core/blob/v10.1.1/apps/files/js/filelist.js#L1773

**Comment by felixheidecke** [comment]
Hmmm … then I guess I need to check the config if it's enabled, and enable SVG based on that.

**Comment by PVince81** [comment]
now thinking, you should only pick the image related mime types from the support preview list

else you'd get previews also for PDF, ODF, etc appearing in the slideshow

**Comment by felixheidecke** [comment]
I'm already filtering ;-)

**Comment by felixheidecke** [comment]
I decided to include a translucent background to the SVG if it's transparent, so no matter the fill, it will show up and stand out from the background.

For those who test, don't forget to enable ImageMagic for SVG support.

**Comment by davitol** [comment]
Cannot open with files_mediaviewer 1.0.0. RC4 + oC 10.2.1 and ImageMagick for PHP on Ubuntu 18.04

The thumbnail is shown, but when I try to open the file, the download dialog appears

@felixheidecke any hints?

**Comment by DeepDiver1975** [comment]
maybe missing/wrong disposition header sent from the server

please inspect the request/response

**Comment by davitol** [comment]
Works, probably a browser cache issue... my bad. Sorry for the noise
