### ISSUE TITLE
Must not preloading all videos instead of just the next and previous one

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_mediaviewer#69]
### Steps

1. Upload three pics and many videos.
1. Rename pics to make sure they appear before the videos in the list
1. Refresh the page
1. Open the network console
1. Open the viewer by clicking on the second picture

### Expected result
Not too many entries preloaded.

### Actual result
Lots of videos preloaded, and each also load a few MB's worth of data. Data stuff already reported here: https://github.com/owncloud/files_mediaviewer/issues/40

![image](https://user-images.githubusercontent.com/277525/56147068-d0df8f00-5fa7-11e9-886c-16f0f5ebd949.png)

This means that on my (slow) server I need to wait quite some time until all the next video data is loaded before I can smoothly swipe through the views. I think here I'd rather have only the next 1-2 videos be loaded but not the next 7 ones, especially if they consume a lot of data.

This might change if there's a way to resolve https://github.com/owncloud/files_mediaviewer/issues/40 to make video previews load faster.

@felixheidecke @pmaier1

**Comment by felixheidecke** [comment]
@PVince81 as discussed, this is where the loading of adjacent images is being handled: https://github.com/owncloud/files_mediaviewer/blob/master/src/scripts/Viewer.vue#L114

**Comment by PVince81** [comment]
that code seems to tell that it should only load **one** previous and **one** next item, but not the whole bunch

from what I observed with 1.0.0RC1 in network console is that it seemed to load a lot of the next videos and pics, if not all of them. can you double check the logic ?

**Comment by PVince81** [comment]
I rechecked again locally on the release-1.0.0 branch and I do see that it's loading all possible pics:

<img width="926" alt="image" src="https://user-images.githubusercontent.com/277525/56592358-cd24bb80-65ea-11e9-963b-0ca19e5efa7f.png">

Here the picture I clicked on is the second one in the list.

Yet you can see that videos are being preloaded, these appear later in the list.
I wonder if this is isolated to videos.

I'll do some other tries with only pics or only videos.

**Comment by PVince81** [comment]
With only pictures in the folder the preload is correctly limited to one previous and one next item.
With only videos in the folder it preloads **all videos**.

With a mix of pictures of videos, it preloads three pictures (current, previous, last) but also preloads **all videos**.

**Comment by PVince81** [comment]
I added some console.log() statements around the call of `shouldRender()` and I noticed that the logic is never called for videos! it's only called for pictures.

this is clearly a bug.

@felixheidecke please have a look

**Comment by PVince81** [comment]
I had another look at the code and it looks easy to fix, I'll have a go at it...

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/files_mediaviewer/pull/71

**Comment by felixheidecke** [comment]
Was fixed in #71
