### ISSUE TITLE
Howto use this for displaying Heic just like JPG or PNG?

### ISSUE THREAD

**Issue by danergo** [owncloud/files_mediaviewer#694]
Installed latest OC, and manually compiled ImageMagick from scratch.

OC has thumbnails for my HEIC and JPG files, but "files_mediaviewer" can display only JPG or PNG files.

How can I convince it to also display HEIC images?

**Comment by danergo** [comment]
bump

**Comment by T0mWz** [comment]
That will help!

**Comment by danergo** [comment]
Noone cares here haha.
