### ISSUE TITLE
Files Mediaviewer 1.0.0 TestPlan

### ISSUE THREAD

**Issue by skshetry** [owncloud/files_mediaviewer#72]
Part of #15 

## 'Files Mediaviewer' Test Plan

- Run Testplan with all supported browsers: Internet Explorer 11, MS EDGE, Mozilla Firefox, Chrome and Safari.

## Testing functionality

Test Case | Expected Result | Result | Related Comment
------------- | -------------- | ----- | ------
**CLI commands** |  |   |
|  |   |
Enable files_mediaviewer app via CLI using ```occ app:enable files_mediaviewer``` | The apps gets enabled | :heavy_check_mark:  |
Disable files_mediaviewer app via CLI using ```occ app:disable files_mediaviewer``` | The apps gets disabled |  :heavy_check_mark: |
**Web UI** |  |   |
|  |   |
Enable files_mediaviewer app via webUI | The apps gets enabled | :heavy_check_mark:  |
Disable files_mediaviewer app via webUI | The apps gets disabled | :heavy_check_mark:  |
**Files View** |  |   |
|  |   |
Open an image file | The viewer should apppear and the image is shown. The correct name of the files appears at the bottom of the viewer. | :no_entry_sign: | Does not work in IE #79
Open a video file | The viewer should appear and the video is shown(unpaused). The correct name of the files appears at the bottom of the viewer. | :no_entry_sign: | Does not work in IE #79  
**MediaViewer Controls** | |:no_entry_sign: | **Does not work in IE #79** *Unless mentioned, all failures below are due to not working in IE (though works in Chrome, Firefox and Edge)* |
|  |   |
Open an image file and click Rotate button | The image gets rotated | :no_entry_sign: |
Open an image file and click Zoom In button | The image gets zoomed in | :no_entry_sign: |
Open an image file and click Zoom out button | The image gets zoomed out | :no_entry_sign: |
Open a media file and click Download button (:arrow_down:) | The media files gets downloaded | :no_entry_sign: |
Open an image file and click "X" button | The viewer disappears | :no_entry_sign: |
Open an image file (in folder having multiple other media files) and click ">"(next) button | The next image should appear | :no_entry_sign: |
Open an image file (with no other media files) and click ">"(next) button | Nothing should happen. The viewer still has old image. | :no_entry_sign: |
Open an image file (in folder having multiple other media files) and click "<"(prev) button | The next image should appear | :no_entry_sign: |
Open an image file (with no other media files) and click "<"(prev) button | Nothing should happen. The viewer still has the old image. | :no_entry_sign: |
Open the last media file in the folder and click ">"(next) button | Nothing should happen. The viewer still has the old image. | :no_entry_sign: |
Open the first media file in the folder and click "<"(prev) button | Nothing should happen. The viewer still has the old image. | :no_entry_sign: |
Open an image and zoom in/zoom out/rotate and open next image | Next image should not be zoomed in/zoomed out/rotated | :no_entry_sign: |
Open an image/video and press :arrow_left:/:arrow_right: key | Previous/Next media files should appear | :no_entry_sign: |
Open an image/video and swipe left/right | Previous/Next media files should appear | :no_entry_sign: |
Open a video file and click play button inside the viewer. | The video starts playing | :no_entry_sign: |
Play a video file, mute sound (:sound:) button and unmute again. | The video plays with sound muted and when unumuted, plays with sound. | :no_entry_sign: | 
Play a video file, and click/press anywhere outside the viewer/control | The video stops playing. | :no_entry_sign: |
Play a video file, and click ⛶ (fullscreen) button. | The video plays in the fullscreen mode.| :no_entry_sign: | Does not work in IE and Edge (maybe intentional)
Play a video file, and click "Replay by 10" button. | The video plays from 10 seconds behind. | :no_entry_sign: |
Play a video file, and click "X" button | The video stops playing and the viewer disappears. | :no_entry_sign: |
Play a video file, and click next/previous button | The video stops playing and the next/previous file should appear. | :no_entry_sign: |
Play a video file, and click anywhere on the scrubber/seek bar | The video skips and plays from the clicked position. | :no_entry_sign: |
Play a video file, and press next/previous button and re-return to the same video and play the video(without ever closing media_viewer) | The video stops playing. When returned to same video, the video plays from the same position previously stopped. | :no_entry_sign: |
Open a unsupported video file | The media viewer shows a helpful message | :no_entry_sign: | Does not show helpful message atm (#35)
Open a details tab with preview, and then open the image file from files list view in the mediaviewer | The media viewer should appear correctly as previous | :no_entry_sign: |
Open a video file and delete the video file in another tab, and try to play the video in first tab | A helpful message should be shown | :no_entry_sign: | #35 
**DetailsDialog View** |  |   |
|  |   |
Open details dialog for a image file, click on the preview/icon of the file and repeat above tests. | | :no_entry_sign:| #73
**Favorites Page** |  |   |
|  |   |
Favorite media files and open Favorites, and repeat above tests. |  | :no_entry_sign: | #73 |
|**Shared with Others Page** |  |   |
|  |   |
Share files with other media files and open `shared with others` page, and repeat above tests. | | :no_entry_sign: | #73
|**Shared with You Page** |  |   |
|  |   |
Share files from other users' account and open `shared with you` page, and repeat above tests. | | :no_entry_sign: | #73
|**Tags Page** |  |   |
|  |   |
Set tags on media files and open `tags` page, and repeat above tests. | | :no_entry_sign: | #73
|**Public Link Page** |  |   |
|  |   |
Share files by public link and open `Share by link` page, and repeat above tests. | | :no_entry_sign: | #73
|**Files Drop** |  |   |
|  |   |
Share a video via files_drop | Check that video plays correctly and buttons work | | Does not seem to be related to `files_mediaviewer`. |
Share a folder via files_drop | Check that the viewer shows all files inside folders and buttons work correctly | :no_entry_sign: | Does not work in IE |

**Comment by skshetry** [comment]
The play button doesnot disappear when the video is played. The control bar also doesnot change to "Pause" button. This worked fine on `master` branch but doesnot work on `RC2` and `release-1.0.0` branch (`release-1.0.0` has some changes that aren't in master).

**Comment by skshetry** [comment]
Play a video file, and click "Replay by 10" button doesnot work on `master` and `RC2`.

**Comment by skshetry** [comment]
Clicking on scrubber/seekbar doesnot work in `RC2`, though works in master.

**Comment by skshetry** [comment]
Opening a video that is not supported by the browser doesnot give helpful information. Similar to #35

**Comment by skshetry** [comment]
Sometimes, the video also does not stop even if the mediaviewer has disappeared. But, have no ways to reproduce.

**Comment by skshetry** [comment]
Swiping by pressing on the media file selects background text and media files.

**Comment by skshetry** [comment]
On Firefox, the viewer appears as follows (with multiple medias in slides mixed up):
![Screenshot from 2019-04-30 16-48-37](https://user-images.githubusercontent.com/18718008/56957754-e0460700-6b67-11e9-8851-d13017776cfd.png)

**Comment by skshetry** [comment]
Sometimes, the video appears as an image.

**Comment by skshetry** [comment]
And, the image appears as the video:
![Screenshot from 2019-04-30 17-02-34](https://user-images.githubusercontent.com/18718008/56958352-d0c7bd80-6b69-11e9-97f0-75ece4477a93.png)

**Comment by skshetry** [comment]
Sometimes, the scrubber doesnot change position when clicked on the different position on the scrubber, though the video changes.

**Comment by PVince81** [comment]
> On Firefox, the viewer appears as follows (with multiple medias in slides mixed up):

@skshetry did you have the Firefox console open or did it happen without it ? see https://github.com/owncloud/files_mediaviewer/issues/68

**Comment by PVince81** [comment]
@skshetry once you're done it would be good to find out how to reproduce the "sometimes" case.
I suspect this could be triggered when modifying the file list after closing the viewer, then opening again. Or maybe opening multiple times from different folders. Maybe you'll find a reproducible scenario for this.

**Comment by skshetry** [comment]
Full screen video playback is only supported on Chrome and Firefox.

**Comment by skshetry** [comment]
Most of the issues should be fixed by #84. IE issues were fixed by #81.

**Comment by felixheidecke** [comment]
@micbar @skshetry is there anything I have to do @ this point?

**Comment by skshetry** [comment]
`files_mediaviewer v1.0.0` has been released. Closing this.
