### ISSUE TITLE
Media Viewer doesnot appear in Favorites page

### ISSUE THREAD

**Issue by skshetry** [owncloud/files_mediaviewer#73]
### Steps to reproduce
1. Favorite few media files.
2. Directly open favorites page or shared with others page. (or, hard reload).
3. Open any media file. 

### Expected Outcome 
The media file appears on the viewer.

### Actual Outcome
Shadow cover the page. No media viewer pops up.

### Why hard reload? 
The media seems to be cached. So, if you:
1. Open `All files` page.
2. Open favorites page (without ever opening the media viewer).
3. Open any media file in the favorites page.

The files from the `All files` page appears.

### Affected Browsers
1. Chrome v73

P.S: The pages that don't work: `Favorites`/`Shared with others`/`Shared by link`/`Tags` pages. I assume `Shared with you` page also don't work.

**Comment by skshetry** [comment]
The `FileList` is available only in `All Files` and `File Drop`. 

https://github.com/owncloud/files_mediaviewer/blob/cc85e0024856fc55e001ec408dcd90908a3d5298/src/scripts/Viewer.vue#L121

`gallery` app seems to get `context`.

https://github.com/owncloud/gallery/blob/e78614a29c096152b6168c0b68f1da656bcf4aa2/js/galleryfileaction.js#L84

whereas, `files_mediaviewer` has this (because, it's deprecated?):
https://github.com/owncloud/files_mediaviewer/blob/cc85e0024856fc55e001ec408dcd90908a3d5298/src/scripts/init.js#L16

**Comment by felixheidecke** [comment]
Funny … I only find [those lines](https://github.com/owncloud/gallery/blob/e78614a29c096152b6168c0b68f1da656bcf4aa2/js/galleryfileaction.js#L51) concerning file registration. I think @PVince81 can point me in the right direction?

**Comment by PVince81** [comment]
@felixheidecke first, did it work with gallery ?

for the favorite list one might need to register on another level but the code you linked to doesn't seem to do so.

as far as I remember, every FileList object including the one of the favorite have their own file actions, so would need to register on those lists too. I don't remember whether there's a way to register file actions for all views.

**Comment by felixheidecke** [comment]
* On my local 11.0.0 prealpha checking `FileList.files` returns an empty array. (After refresh)
* The online demo.owncloud.com 10.2.0 checking `FileList.files` returns a properly populated array
* … hmmm

**Comment by skshetry** [comment]
@felixheidecke Did you refresh and test on `demo.owncloud.com`? I think, `FileList` gets binded to window only when first loaded.

**Comment by felixheidecke** [comment]
On deeper inspection, the gallery fills its list from the actionHandler context. So I adopted the approach which made it necessary to store the list in `OCA.Mediaviewer` because the media viewer initializes after the redirect which can't hold a payload.

**Comment by skshetry** [comment]
Fixed in #87
