### ISSUE TITLE
Photo gets rotated instead of zoom in

### ISSUE THREAD

**Issue by davitol** [owncloud/files_mediaviewer#89]
### Steps to reproduce

1 - Upload a photo
2 - Open the photo with Safari browser
3 -  Try to zoom in

### Expected behaviour

Photo zooms in

### Actual behaviour

Photo gets rotated

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1

**ownCloud version:**

ownCloud 10.2.1 
**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
No logs in owncloud.log
```

### Client configuration

**browser**

Safari Version 12.0.2 (13606.3.4.1.4)

**Comment by davitol** [comment]
Looks like it was a temporaly bug and cannot be reproduced consistenly, let's close for now

**Comment by davitol** [comment]
https://cloud.owncloud.com/index.php/s/tU3IiW9mETVpTtr

**Comment by davitol** [comment]
cc @felixheidecke

**Comment by felixheidecke** [comment]
I'm not able to reproduce this bug. @davitol does this now happen in all browsers?

**Comment by davitol** [comment]
> I'm not able to reproduce this bug. @davitol does this now happen in all browsers?

Cannot reproduce it too now, seems like a random bug. I will close the ticket and reopen again if I get how to reproduce it consistenly
