### ISSUE TITLE
Dropdown menu is ugly and misses icon

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/files_mediaviewer#96]
![Screenshot from 2019-07-11 12-31-52](https://user-images.githubusercontent.com/1005065/61044020-fd088180-a3d7-11e9-9f6c-16db3e7d6f4c.png)

**Comment by davitol** [comment]
@DeepDiver1975 Does it happen to you in the released 1.0.0 version?

It does not appear to me in the files view with files_mediaviewer: 1.0.0 enabled

![Screen Shot 2019-07-16 at 16 32 29](https://user-images.githubusercontent.com/10596560/61303192-6678fd80-a7e7-11e9-9e78-f34e3b92e402.png)

(cc @cdamken , @pmaier1 does it happen to you too?)

**Comment by DeepDiver1975** [comment]
I installed it from marketplace - version 1.0.0

I'm running ownCloud 10.1.1

**Comment by pmaier1** [comment]
For me the entry is also not shown.

**Comment by felixheidecke** [comment]
Strange … I also don't see that dropdown menu. How does it work?

**Comment by davitol** [comment]
Tested with ownCloud 10.1.1, files_mediaviewer from market and several media files and browsers. Cannot reproduce it. Let's close the ticket. @DeepDiver1975 feel free to reopen if you can reproduce the issue consistently
