### ISSUE TITLE
Some MP4 Videos are not displayed, but you can hear the music/sounds

### ISSUE THREAD

**Issue by cdamken** [owncloud/files_mediaviewer#98]
An example:

https://cloud.damken.com/index.php/s/pZJ1nB3hUZEpwew

(Available until the end of September 2019)

**Comment by cdamken** [comment]
I can see the video with the old video-viewer app, only when I download it.

**Comment by felixheidecke** [comment]
![FireShot Capture 027 - Another friendly cloud in the cyberspace - cloud damken com](https://user-images.githubusercontent.com/12717530/61701338-447b0000-ad3e-11e9-866f-9272102c5f15.png)

@cdamken This is not the mediaviewer app ;-)
